/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesCaseIdGraphRouteImport } from './routes/cases/$caseId/graph'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdGraphRoute = CasesCaseIdGraphRouteImport.update({
  id: '/cases/$caseId/graph',
  path: '/cases/$caseId/graph',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases/$caseId/graph': typeof CasesCaseIdGraphRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases/$caseId/graph': typeof CasesCaseIdGraphRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases/$caseId/graph': typeof CasesCaseIdGraphRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cases/$caseId/graph'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cases/$caseId/graph'
  id: '__root__' | '/' | '/cases/$caseId/graph'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesCaseIdGraphRoute: typeof CasesCaseIdGraphRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId/graph': {
      id: '/cases/$caseId/graph'
      path: '/cases/$caseId/graph'
      fullPath: '/cases/$caseId/graph'
      preLoaderRoute: typeof CasesCaseIdGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesCaseIdGraphRoute: CasesCaseIdGraphRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
